apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e09wzny8k-go-gitops
  description: This is GitOps manifest for e09wzny8k-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=e09wzny8k-go
    backstage.io/kubernetes-id: e09wzny8k-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: e09wzny8k-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:e09wzny8k-go
