apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e09wzny8k-go
  janus-idp.io/tekton: e09wzny8k-go
  backstage.io/kubernetes-id: e09wzny8k-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e09wzny8k-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
